# sfm algorithm configure
social_force:
  animation_factor: 5.1
  # only handle pedestrians within `people_distance`
  people_distance: 6.0
  # weights of social force model
  goal_weight: 2.0
  obstacle_weight: 20.0
  social_weight: 15
  group_gaze_weight: 3.0
  group_coh_weight: 2.0
  group_rep_weight: 1.0

# pedestrians setting
pedestrians:
  update_rate: 5
  ped_property:
    - name: human_1
      pose: 3 2 1 0 0 0
      velocity: 0.9
      radius: 0.4
      cycle: true
      ignore:
        model_1: ground_plane
        model_2: turtlebot3_waffle
      trajectory:
        goal_point_1: 3 2 1 0 0 0
        goal_point_2: 3 -8 1 0 0 0
    - name: human_2
      pose: -0.5 -8.5 1 0 0 0
      velocity: 1.2
      radius: 0.4
      cycle: true
      ignore:
        model_1: ground_plane
        model_2: turtlebot3_waffle
      trajectory:
        goal_point_1: -0.5 -8.5 1 0 0 0
        goal_point_2: -9 2.5 1 0 0 0
    - name: human_3
      pose: -3.5 -8.5 1 0 0 0
      velocity: 1.2
      radius: 0.4
      cycle: true
      ignore:
        model_1: ground_plane
        model_2: turtlebot3_waffle
      trajectory:
        goal_point_1: 0 -5 1 0 0 0
        goal_point_2: -3.5 6 1 0 0 0
    - name: human_4
      pose: 0 0 1 0 0 0
      velocity: 1.2
      radius: 0.4
      cycle: true
      ignore:
        model_1: ground_plane
      trajectory:
        goal_point_1: -1 -3 1 0 0 0
        goal_point_2: 5 2.5 1 0 0 0
        goal_point_3: 0 0 1 0 0 0
    - name: human_5
      pose: 1 -2 1 0 0 0
      velocity: 2
      radius: 0.4
      cycle: true
      ignore:
        model_1: ground_plane
      trajectory:
        goal_point_1: 3 2 1 0 0 0
        goal_point_2: -0.5 -8.5 1 0 0 0
    - name: human_6
      pose: -1.2 2.3 1 0 0 0
      velocity: 2.1
      radius: 0.4
      cycle: true
      ignore:
        model_1: ground_plane
        model_2: turtlebot3_waffle
      trajectory:
        goal_point_1: 3 -8 1 0 0 0
        goal_point_2: -9 2.5 1 0 0 0
    - name: human_7
      pose: -3 2 1 0 0 0
      velocity: 1.4
      radius: 0.4
      cycle: true
      ignore:
        model_1: ground_plane
        model_2: turtlebot3_waffle
      trajectory:
        goal_point_1: 3.5 8.5 1 0 0 0
        goal_point_2: -3.4 4 1 0 0 0
    - name: human_8
      pose: 1 0.2 1 0 0 0
      velocity: 2
      radius: 0.4
      cycle: true
      ignore:
        model_1: ground_plane
        model_2: turtlebot3_waffle
      trajectory:
        goal_point_1: -3.5 8.5 1 0 0 0
        goal_point_2: -3.4 -8.5 1 0 0 0
    - name: human_9
      pose: 0.7 0.3 1 0 0 0
      velocity: 2
      radius: 0.4
      cycle: true
      ignore:
        model_1: ground_plane
        model_2: turtlebot3_waffle
      trajectory:
        goal_point_1: -1 -5.7 1 0 0 0
        goal_point_2: 5 2 1 0 0 0
